/*
DB0
Global

gallexy 0,1
ship
user

============================
DB1
gallexy 2,3
ship
user

TODO
1. isolation level repetable read 격리수준 적용
2. transaction 적용

*/


DROP DATABASE IF EXISTS yoda;
CREATE DATABASE IF NOT EXISTS yoda;
USE yoda;

/* Create table */
CREATE TABLE galaxy (
	GID TINYINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(16),
	HP INT,
	PRIMARY KEY(GID)
);

CREATE TABLE user (
	UID INT NOT NULL,
	GID TINYINT,
	FOREIGN KEY (GID) REFERENCES galaxy(GID),
	PRIMARY KEY(UID, GID)
);

CREATE TABLE slog (
	LOGID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	UID INT,
	LOG VARCHAR(64),
	LOG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ship (
	SUD INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	UID INT,
	GID TINYINT,
	FOREIGN KEY (UID, GID) REFERENCES user(UID, GID),
	ATK INT
);

CREATE TABLE db (
	DBID TINYINT,
	DBNAME CHAR(3),
	IP CHAR(15),
	PORT INT
);

CREATE TABLE user2db (
	USERID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	GID TINYINT,
	DBID TINYINT
);

/* Insert Initial Data */
INSERT INTO db '';
INSERT INTO galaxy(NAME, HP) VALUES("MILKYWAY1", 100000);
INSERT INTO galaxy(NAME, HP) VALUES("MILKYWAY2", 100000);

/* Create table */
CREATE TABLE galaxy (
	GID TINYINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(16),
	HP INT,
	PRIMARY KEY(GID)
);
/*
 * TODO: Galaxy 테이블 초기데이터 넣기
 * TODO: DB 테이블 초기데이터 넣기
 */


/* Master Join Procedure */
DROP PROCEDURE IF EXISTS ADDUSER;
DELIMITER &&
CREATE PROCEDURE ADDUSER(OUT RUID INT, OUT RDBID INT, OUT RGID TINYINT)
	BEGIN
		START TRANSACTION;
		INSERT INTO user2db values();
		set RUID = last_insert_id();
		set RGID = RUID % 4;
		set RDBID = RGID % 2 + 1;
		UPDATE user2db SET DBID = RDBID, GID = RGID WHERE USERID = RUID;
		COMMIT;
	END &&
DELIMITER ;

CALL ADDUSER(@RUID, @RDBID, @RGID);

SELECT @RUID;
SELECT @RDBID;
SELECT @RGID;

/* Individual Join Procedure */
/* Master Join Procedure */
DROP PROCEDURE IF EXISTS ADDUSER_SHARD;
DELIMITER &&
CREATE PROCEDURE ADDUSER_SHARD(IN UID INT, IN GID TINYINT)
	BEGIN
		DECLARE idx INT DEFAULT 0;
		START TRANSACTION;
		INSERT INTO user VALUES(UID, GID);
		
		
		WHILE idx < 10 DO
			INSERT INTO ship(UID, GID, ATK) VALUES(UID, GID, ROUND((RAND() * (100-5))+5));
			SET idx = idx + 1;
		END WHILE
		COMMIT;
	END &&
DELIMITER ;


/* Log */
DROP PROCEDURE IF EXISTS LOG;
DELIMITER $$
CREATE PROCEDURE LOG(IN UID INT, IN LOGTXT VARCHAR(128))
BEGIN
INSERT INTO slog(UID, LOG, LOG_TIME) VALUES (UID, LOGTXT, current_time());
END $$
DELIMITER ;